language: python
dist: precise
python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade pytest pytest-asyncio -rrequirements.txt .

script:
  - python -m pytest tests/
